####################
# 框架配置
####################
server:
  port: 9090
management:
  security:
    enabled: false
spring:
  jackson:
    serialization:
      indent-output: true

####################
# 基础配置
####################
umf:
  profile: ASIA_TEST
  clientId: 383e1d786cad37cbe4c5fd926aef09b546479f62 # 测试
  clientSecret: 58f3f567fe7d973c08417a1edc6dbe238cd71246
